### ISSUE TITLE
Hold to reset no longer working

### ISSUE THREAD

**Issue by DENightOne** [a-p-z/datetime-card#20]
Hi there, firstly thanks for the great card, helps me remember to do maintenance around the house.  I have no idea when this started happening as i only have to click on reset every 100 days or more, but I noticed after the last update that when I hold down to reset nothing happens anymore. this is the error that I get when I look at the web developer console: 

TypeError: s.buttonTapped is not a function.

Home Assistant 2023.9.1
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest

I can still manually change the value of the input_date using the entities tab in settings, but the hold to reset was a great feature.

this error could be totally unique to me, but I thought I would put it here just in case others are having the same issue

**Comment by Gawronnek** [comment]
Unfortunately, I have the same error

**Comment by a-p-z** [comment]
Thanks for opening the issue. I will try to have a look during this weekend.
