### ISSUE TITLE
no click-on set date

### ISSUE THREAD

**Issue by Protoncek** [a-p-z/datetime-card#3]
Hello!
I love your card, great work. It's just one thing more it would ne nice to have: the possibility to click on entity and set/change date. Is that possible to add? I'll use it as a note for dog water fountain filter replacement (to set date when it was replaced)
Thanks!

**Comment by a-p-z** [comment]
thanks for the message.
you cannot set the date but you can reset it. if you click/touch on the bar or on the days text for few seconds the date is set to the current day
https://github.com/a-p-z/datetime-card/blob/5805f51315145e65579b640b640f1c931f65612f/src/DatetimeBar.svelte#L47

**Comment by Protoncek** [comment]
AHA! Great, that's all i need - to set date to "today". Many thanks!
