### ISSUE TITLE
FR: make new date formatting optional

### ISSUE THREAD

**Issue by erkr** [a-p-z/datetime-card#33]
The latest version introduced new date formatting (months, days).
This option significantly reduces the bar length (mobile view) and the names in the bars are not fully visible as a result:
![image](https://github.com/a-p-z/datetime-card/assets/4363599/3a54ed03-e4e7-40c9-b3bb-9328a6215a54)

Please make this new date formatting optional (card option).

Best Eric

**Comment by erkr** [comment]
Some 2nd thoughts: the meaning of the 'days' is not clear by it self (are those days since? or days left? or days total?). That is the main reason I put extra into in the name.
In stead of an option to switch between the old style days or this new data formatting, I can imagine a number of more options:
- hide 
- only days since (old)
- formatted days since (new)
- templated (user can compose everything with support of 2 variables: 'max' and 'passed').  This would allow a lot of options for the user, examples:
    - short styles:
      - When 3 days to go before expired: "11 (of 14)" so 11 days passed of the total. 
      - On the day it expires: "14 (of 14)"
      - When 2 days ago expired: "16 (of 14 )"
    - long styles:
      - When 3 days to go before expired: "11 (of 14) passed"
      - On the day it expires: "14 (of 14) expired"
      - When 2 days ago expired: "16 (of 14 ) behind"
      
Just as input for thought :-)

**Comment by a-p-z** [comment]
https://github.com/a-p-z/datetime-card/releases/tag/v1.0.6

**Comment by erkr** [comment]
Thanks for making it optional (format_label) 👌
Best Eric

**Comment by a-p-z** [comment]
you are welcome!
