### ISSUE TITLE
Date reset not using local date

### ISSUE THREAD

**Issue by kaizersoje** [a-p-z/datetime-card#34]
I have noticed the date reset is not using the date in the local timezone.

I am trying to reset an entity and it shows up yesterday's date (2024/05/19) instead of today's date (2024/05/20).
![image](https://github.com/a-p-z/datetime-card/assets/54566217/0b57874d-a08c-4018-81a0-7891bfcf5180)

![image](https://github.com/a-p-z/datetime-card/assets/54566217/794e8ee2-bd3d-468a-930a-8c923458adc4)

**Comment by a-p-z** [comment]
Hi @kaizersoje, thanks for reporting the issue.
Is the date wrong only in the confirmation message?
Or the date of the entity is wrong after the reset too?

**Comment by kaizersoje** [comment]
> Hi @kaizersoje, thanks for reporting the issue. Is the date wrong only in the confirmation message? Or the date of the entity is wrong after the reset too?

It is setting the date on both the message and after reset

**Comment by a-p-z** [comment]
https://github.com/a-p-z/datetime-card/releases/tag/v1.0.6
