### ISSUE TITLE
Date not getting reset after upgrading to 2024.8.x

### ISSUE THREAD

**Issue by kaizersoje** [a-p-z/datetime-card#37]
After upgrading to HA version 2024.8.x, when I try to reset the entity, I get the following error.

![image](https://github.com/user-attachments/assets/466fe3d0-9172-4a8a-aabe-d92fc95a53eb)

**Comment by a-p-z** [comment]
resolved in https://github.com/a-p-z/datetime-card/releases/tag/v1.0.6
