### ISSUE TITLE
Feature request: notifiers

### ISSUE THREAD

**Issue by erkr** [a-p-z/datetime-card#4]
Thanks for publishing this card. elegantly simple. It would be nice if the card allows to configure a notifier in case the max duration gets exceeded. In the ToDo a dnd is mentioned. It’s that a  Do not disturb? The combo would be great. notifiers with a dnd option.
best Eric

**Comment by a-p-z** [comment]
Dear Eric, dnd in the to-do list means drag and drop, I would like to add the possibility to order the entity using the mouse.

Regarding your request, when the time exceeds the badge icon and the bar become red.
If I correctly understood you want to execute any action, like a notification.
In this case, you have to define an automation.
Cards give you a visual view of the current state, they do not perform any action.

**Comment by erkr** [comment]
Clear. Many possibilities for the acronym DND 😊. True: notification can be done via automatons, but not the option to enable or mute them in the card. Thanks for answering!

**Comment by a-p-z** [comment]
You can always use a card with a switch to enable/disable the automation

**Comment by erkr** [comment]
I know, every automation is already available as a switch. Have them combined in one card could  be a nice option. But that is up to you as the author👍
