### ISSUE TITLE
Feature request: name option

### ISSUE THREAD

**Issue by erkr** [a-p-z/datetime-card#5]
Please consider to add a name field option to the entities. Some entities have the same icon.
Best Eric

**Comment by shadowdavis** [comment]
Yes, it is important to support adding names，thanks alot！

**Comment by a-p-z** [comment]
I agree.
Let's see if the component is successful among the community ...
if I take a few stars, I will invest some time in this and other improvements

**Comment by shadowdavis** [comment]
> 



> I agree.
> Let's see if the component is successful among the community ...
> if I take a few stars, I will invest some time in this and other improvements

Thanks and starred! This card is not just for taking care of plants. For example, I want to use it to record the life of the filter element of my air purifier or water purifier, or the membership subscription service that needs to be renewed, or to record the days when the car needs maintenance, etc. It really has a wide range of uses!

**Comment by a-p-z** [comment]
Yes, I know.
I wrote in the description just two use cases but there are many.
We can create a page and list other examples

**Comment by erkr** [comment]
My usage is similar to what shadowdavis mentioned (a list of filter/battery replacements etc) So I don’t user the image option. In my case, I would love to have the  name printed  @ the left of the icons, in order to more  easily discriminate them:
![950E2D40-EBE8-4D6B-9A5D-B69BE2AD099D](https://user-images.githubusercontent.com/4363599/170325343-a231a6d3-52f9-4dc0-98c1-2975066ef270.jpeg)

**Comment by a-p-z** [comment]
implemented in [v1.0.1](https://github.com/a-p-z/datetime-card/releases/tag/1.0.1)

**Comment by erkr** [comment]
This is done really nice, I like it👍👍

**Comment by shadowdavis** [comment]
Really nice！！
