### ISSUE TITLE
datetime being set to midnight UTC

### ISSUE THREAD

**Issue by kaizersoje** [a-p-z/datetime-card#6]
I have noticed that on resetting an entity, it is being reset to midnight UTC and not taking into account the local time. For eg: I reset an entity at 8AM 6/6/22 (UTC+10). However, the state of the entity shows as 5/6/22 in developer tools.

**Comment by a-p-z** [comment]
Yes, I know.
As first implementation I did not take in consideration the local time. I will fix it in the next release.
https://github.com/a-p-z/datetime-card/blob/main/src/datetime/datetime.ts#L14
